from abc import ABC, abstractmethod

class Engine(ABC):
    @abstractmethod
    def compile(self) -> str: ...
    @abstractmethod
    def from_id(self, id: int) -> list[str]: ...
    @abstractmethod
    def assemble(self, lines: list[str]) -> str: ...
    @abstractmethod
    def save(self, code: str) -> str: ...
    @abstractmethod
    def gen(self, id: int): ...
